CREATE DATABASE MUSICALINSTRUMENT
GO
USE MUSICALINSTRUMENT
GO

CREATE TABLE USERS 
(
	USERNAME VARCHAR(20) PRIMARY KEY NOT NULL,
	PASSWORDS VARCHAR(30),
	FULLNAME NVARCHAR(50),
	ROLES INT,
	STATUSS INT
)
GO

CREATE TABLE PRODUCT
(
	ID VARCHAR(15) PRIMARY KEY NOT NULL,
	MNAME NVARCHAR(100),
	IMAGES VARCHAR(100),
	CATEGORY NVARCHAR(50),
	MANUFACTURER NVARCHAR(100),
	PRICE INT,
	NUMBER INT,
	DESCRIPTIONS NTEXT,
	STATUSS INT
)
GO
CREATE TABLE BILL
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SENDER NVARCHAR(50),
	RECEIVER NVARCHAR(50),
	DATECREATE DATE,
	STATUSS INT
)
GO
CREATE TABLE BILLDETAIL
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BILLID INT,
	PRODUCTID INT,
	NUMBER INT,
	STATUSS INT
)
GO
CREATE TABLE ORDERS
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SELLER NVARCHAR(50),
	BUYER NVARCHAR(50),
	BUYERPHONENUMBER VARCHAR(20),
	PRODUCT INT,
	PRODUCTNUMBER INT,
	MONEYRECEIVED INT,
	EXCESSCASH INT,
	DATECREATE DATE,
	STATUSS INT
)